import Head from 'next/head'

import SectionVideo from '../sections/SectionVideo'
import SectionSponsors from '../sections/SectionSponsors'
import SectionTracks from '../sections/SectionTracks'
import SectionSocialMedia from '../sections/SectionSocialMedia'
import SectionArtists from '../sections/SectionArtists'
import SectionFooter from '../sections/SectionFooter'

import Image from 'next/image'

export default function Home() {
  return (
    <div className='h-screen overflow-y-scroll overflow-x-hidden scrollbar scrollbar-hidden p-3 md:px-16'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section id="hero">
        <SectionVideo />
      </section>

      <section id="sponsors">
        <SectionSponsors />
      </section>

      <section id="tracks">
        <SectionTracks />
      </section>

      <section id='socialmedia'>
        <SectionSocialMedia />
      </section>

      <section id='artists'>
        <SectionArtists />
      </section>

      {/* <section id="sponsors" className='snap-center'>
        <SectionSponsors />
      </section>

      <section id="tracks" className='snap-center px-8 text-'>
        <SectionTracks />
      </section>

      <section id='socialmedia' className='snap-center'>
        <SectionSocialMedia />
      </section>

      <section id='artists' className='snap-center'>
        <SectionArtists />
      </section>

      <section id='footer' className='snap-center'>
        <SectionFooter />
      </section> */}
    </div>
  )
}
