import Head from 'next/head'

import SectionVideo from '../sections/SectionVideo'
import SectionSponsors from '../sections/SectionSponsors'
import SectionTracks from '../sections/SectionTracks'
import SectionSocialMedia from '../sections/SectionSocialMedia'
import SectionArtists from '../sections/SectionArtists'
import SectionFooter from '../sections/SectionFooter'

export default function Home() {
  return (
    <div className='h-screen overflow-y-scroll snap-y snap-normal scrollbar scrollbar-track-black scrollbar-thumb-stone-50'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section id="hero" className='snap-start'>
        <SectionVideo />
      </section>

      <section id="sponsors" className='snap-center'>
        <SectionSponsors />
      </section>

      <section id="tracks" className='snap-center'>
        <SectionTracks />
      </section>

      <section id='socialmedia' className='snap-center'>
        <SectionSocialMedia />
      </section>

      <section id='artists' className='snap-center'>
        <SectionArtists />
      </section>

      <section id='footer' className='snap-center'>
        <SectionFooter />
      </section>
    </div>
  )
}
